title: André Oliveira
description: Welcome to my portfolio! With 3+ years of experience working as analyst, I am disciplined, passionate and eager to learn. I consistently invest considerable effort in advancing my skills and knowledge to drive continuous professional growth and deliver substantial value to both my organisation and colleagues.
I am a team player who is always prepared to brainstorm with a focus on problem-solving.
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
