title: André Oliveira
description: With 3+ years of experience working as analyst, I am disciplined, passionate and eager to learn.
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
